### ISSUE TITLE
Error checking

### ISSUE THREAD

**Issue by t94j0** [evilsocket/xray#13]
I see a lot of `if err == nil` checks, but I don't see you handling errors at all. It might be a good idea to handle and log the errors. It seems like many of the errors can be logged as informational, but some errors like [this](https://github.com/evilsocket/xray/blob/master/http_grabber.go#L192) may want to be logged as a warning, or even [this](https://github.com/evilsocket/xray/blob/master/cmd/xray/main.go#L53) as an error.

**Comment by evilsocket** [comment]
Dude did you try to spend 5 minutes to think **why** I'm ignoring some errors and I'm just panic-ing on others?

The errors I'm ignoring, are not fatal errors (like a closed port, or a non existent domain not being resolved), due to the very nature of this tool, if I'd follow your suggestion, the user would have the terminal full of completely useless log messages.

Try to put just a fmt.Println [here](https://github.com/evilsocket/xray/blob/master/cmd/xray/main.go#L53) and see what happes :)

**Comment by t94j0** [comment]
Haha, yeah. That'd be a wall of text.
I just think that some of the errors may want to be logged to a file for informational reasons so that users can troubleshoot configuration issues they may have. If you don't think this tools needs it, then I totally understand. It's just an idea. 😄 😸

**Comment by evilsocket** [comment]
So far you only provided places where the error **must not** be logged at all, if you give me real examples of the usefulness of such logging I'll gladly add it.
