### ISSUE TITLE
[Feature Requests] Screenshot & S3 Buckets

### ISSUE THREAD

**Issue by random-robbie** [evilsocket/xray#21]
Hey Dude,

Can you add a screenshot system for when it hits pages that are responding with http so it can help work out what the pages are?

also on s3 buckets like this one..
[![Capture.png](https://s23.postimg.org/zbo52k3sr/Capture.png)](https://postimg.org/image/8du80tj5j/)

can you have it so it grabs the bucketname?

view-source:http://js.mapbox.com/

shows [![Capture.png](https://s12.postimg.org/5m83qijtp/Capture.png)](https://postimg.org/image/mzie5df4p/)

which would be very handy to know it's on a s3 bucket and then i can check permissions of the bucket :)

**Comment by evilsocket** [comment]
I thought about screenshots, but if you think about it, they're quite pointless ... in order not to break the html layout, let's say I put the image as a small thumbnail on the right ... you have to click on it in order to see it ... so what's the difference of just clicking on a link and see for yourself what the page is? :D

Working on the Amazon thingy ;)

**Comment by madaratech** [comment]
@evilsocket, screenshot give us better idea to what loos 1st, handy in case of when u have like tons of subdomains, so you will better pick the target what u see, instead of clicking on every link!

**Comment by evilsocket** [comment]
@madaratech **again**, you'd have to click on each screenshot anyway.

**Comment by madaratech** [comment]
@evilsocket  can't we see thumbnails or picture ? i mean we will click on what we see more understandable or easy to start the test, in other case, you will click on everything to see what application it is.

**Comment by evilsocket** [comment]
I'll write only once again ...

The only way to do this, would be putting screenshots in a new column on the table. But in order not to break the table, I'd need to set the screenshot size to a thumbnail, let's say 200x200 at most.

Now you have a bunch of 200x200 images which you have to click anyway since they're too small ... therefore, there'd be no difference between this and clicking on the links.

**Comment by madaratech** [comment]
hmm, UI conflict i see, that's understandable!

anyway in future, if you plan to update UI, consider this also in mind, it will good add in future!

Thanks for making it :)
